name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Instalar binario de Cypress
        run: pnpm exec cypress install

      - name: Ejecutar tests
        run: pnpm exec cypress run --browser chrome --spec "cypress/e2e/Correcto/**/*.cy.js"

      - name: Subir reporte HTML
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reporte-cypress
          path: cypress/reports

      - name: Subir capturas
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: capturas
          path: cypress/screenshots