name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
      - name: Ejecutar tests de Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/Correcto/**/*.cy.js

      - name: Subir reporte HTML
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reporte-cypress
          path: cypress/reports

      - name: Subir capturas
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: capturas
          path: cypress/screenshots

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Instalar binario de Cypress
        run: pnpm exec cypress install

      - name: Ejecutar tests de Cypress
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: chrome
          spec: cypress/e2e/Correcto/**/*.cy.js    